using System;
using System.IO;
using System.Collections;
using System.Collections.Generic;

/*
 * The MIT License (MIT)

Copyright (c) 2021 Paul Cardno

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
SOFTWARE.

Mega simple file splitter because I keep getting massive CSV files (2million+ lines) that I need to break down to be loadable into Excel
Doesn't work with autogenerated JSON as that's only ever a single line (that'll be another program).

*/
namespace FileSplitter
{
    class Program
    {
        static void Main(string[] args)
        {
            

            string[] lines = File.ReadAllLines(@"C:\wipro\levoutput-images-cutdown-2021-10-06-17-35-43.csv");

            int counter = 1;

            int fileCount = 1;

            Dictionary<int, List<string>> buffer = new();

            buffer.Add(1, new List<String>());

            foreach(string line in lines)
            {
                buffer[fileCount].Add(line);

                counter++;

                if (counter % 100000 == 0)
                {
                    fileCount++;

                    buffer.Add(fileCount, new List<string>());
                }
            }


            foreach(int key in buffer.Keys)
            {
                File.WriteAllLines(String.Format("C:\\wipro\\levoutput-images-cutdown-2021-10-06-17-35-43-split{0}.csv", key), buffer[key]);
            }
            Console.WriteLine("All done!");


        }
    }
}
